### ISSUE TITLE
"scalar(%hash)" return signature changed

### ISSUE THREAD

**Issue by eserte** [bayashi/Plack-Middleware-EnvTracer#1]
t/05_scalar.t fails with perl 5.25.3 and newer:

```
#   Failed test at t/05_scalar.t line 30.
#                   '<html><body><p>scalar:56</p></body></html>'
#     doesn't match '(?^:<p>scalar:\d+/\d+</p>)'
# Looks like you failed 1 test of 6.
t/05_scalar.t ............ 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/6 subtests 
```

This looks like this change mentioned in perl5.25.3's perldelta:

>  "scalar(%hash)" return signature changed
>    The value returned for "scalar(%hash)" will no longer show information
>    about the buckets allocated in the hash. It will simply return the count
>    of used keys. It is thus equivalent to "0+keys(%hash)".
> 
>    A form of backwards compatibility is provided via
>    "Hash::Util::bucket_ratio()" which provides the same behavior as
>    "scalar(%hash)" provided prior to Perl 5.25.

**Comment by bayashi** [comment]
@eserte 
Thank you for reporting.
I've fixed it on version 0.02.
